# Generated by Django 5.0.6 on 2024-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.CharField()),
            ],
            options={
                'db_table': 'boards',
            },
        ),
    ]
